name: ci

on: push

jobs:
  # Run the phoenix unittests.
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-elixir@v1.1.0
        with:
          otp-version: 22.x
          elixir-version: 1.9.x

      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Check formatting
        run: mix format --check-formatted

      - name: Run Tests
        run: |
          mix test

  # Use dializer to typecheck.
  typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-elixir@v1.1.0
        with:
          otp-version: 22.x
          elixir-version: 1.9.x

      - name: Cache Dialyzer typings
        uses: actions/cache@v1
        env:
          cache-name: cache-typings
        with:
          path: priv/plts
          key: build-${{ env.cache-name }}-${{ hashFiles('mix.lock') }}

      - name: Install dependencies
        run: mix deps.get

      - name: Run Dialyzer
        run: mix dialyzer
